### ISSUE TITLE
minishell test case 점검

### ISSUE THREAD

**Issue by Hyoj-Kim** [minishell-jiphyeonjeon/Rank03-Minishell#110]
### file
- [x] #129
- [x] ls시 `Conditional jump or move depends on uninitialised value(s)` 에러 발생

### exit
- [x] #119
- [x] exit 뒤의 인자가 2개 이상이면 too many arguments error (종료 안됨, exitcode: 1)
- [x] #126

### redirect
- [x] #116
현재 cat 무한대기
- [x] #127
- [x] heredoc 종료후 fd 계속해서 열려있음

### cd
- [x] #117
`cd ~`: 홈 디렉토리로 이동 
- [x] `cd`: 홈 디렉토리로 이동
- [x] #114
현재 error 출력 후 프로그램이 아예 종료됨
- [x] #125

### pwd
- [x] #114
현재 error 출력 후 프로그램이 아예 종료됨

### env & export
- [x] #111
- [x] #112
현재 env에 그냥 추가되고 있음
parser에서 $뒤에 오는 변수명 규칙을 export에서도 그대로 따름. is_함수 그대로 이용가능 할 것으로 추정
- [x] #113
처음엔 scanner에서 해야하나 싶었는데, 그냥 문자열은 제대로 출력해야하므로 환경변수 추가할 때 처리해야할 듯

### ETC
- [x] #132
현재 아무동작도 안하는 것은 맞지만 exitcode가 1로 설정됨

**Comment by scarf005** [comment]
### Redirect
- [ ] `echo test > ls -> cat ls`
- [ ] `echo test > ls >> ls >> ls -> echo test >> ls -> cat ls`
- [ ] `> test echo test hello -> cat test`
- [ ] `>test echo > a>b>a>>b>a mdr >b a >a -> cat a`
- [ ] `cat ls`
- [ ] `cat < ls`
- [ ] `cat < ls > ls`
- [ ] `<< eof cat >> infile -> infile 뒤에 추가됨`
- [ ] `<< HERE_DOC > a.txt | cat a.txt | wc -l`
- [ ] `<< HERE_DOC > a.txt | cat a.txt`
- [ ] `ls -al | > a.txt`
- [ ] `ls -al | cat`
