### ISSUE TITLE
export시 공백이 제대로 처리되지 않음

### ISSUE THREAD

**Issue by scarf005** [minishell-jiphyeonjeon/Rank03-Minishell#113]
```bash
export TEST="ls             -l           - a" 
echo $TEST: `ls -l - a`
```
> 공백이 무조건 하나만 처리됨
처음엔 scanner에서 해야하나 싶었는데, 그냥 문자열은 제대로 출력해야하므로 환경변수 추가할 때 처리해야할 듯

**Comment by Hyoj-Kim** [comment]
윽... env까지는 맞게 공백 그대로 가져가는게 맞네요ㅠㅠ 이건 expander에서 "$TEST"인지, $TEST인지 확인하고 처리하도록 하겠습니다!
