### ISSUE TITLE
tokenizer 문자열 처리 추가

### ISSUE THREAD

**Issue by Hyoj-Kim** [minishell-jiphyeonjeon/Rank03-Minishell#36]
### `"`과 `'`로 감싸진 문자열이 문자열 중간에 위치할 때 처리
- [x] hello" $USER "world -> hello" $USER "world
- [x] hello" user "world -> hello user world
- [x] hello' $USER 'world -> hello $USER world
- [x] hello' user 'world -> hello user world

### 따옴표 없는 expansion 문자열 처리
- [x]  hello$USER -> "hello$USER"
- [x]  hello${USER}world -> "hello${USER}world"

**Comment by scarf005** [comment]
테스트 케이스 추가:

- [ ] echo a ${USER}asfd is at[$HOME] asdf $afsfas "they are in$HOME"

```bash
a youkimasfd is at[/Users/youkim] asdf they are in/Users/youkim
```

**Comment by Hyoj-Kim** [comment]
테스트케이스의 경우 bash-parser를 참고했을 때 환경변수와 매칭이 되는 경우는 그냥 그대로 token화 되었다가 parsing 단계에서 start와 end만 제대로 지정해주면 되는 것 같습니다.

str_new_split(str, '  ')은 임시로 테스트하기 위해서 쓰는 것입니다! `'`과 `"` 처리는 무조건 tokenizer에서 하도록 설계해놓은 상태입니다.
