### ISSUE TITLE
makefile에서 `make`실행시 컴파일이 시작되지 않음

### ISSUE THREAD

**Issue by scarf005** [minishell-jiphyeonjeon/Rank03-Minishell#77]
### 개요
make all:
```c
❯ make all
[prompt]  prompt.c -> prompt.o
[prompt]  interrupt.c -> interrupt.o
[prompt]  util.c -> util.o
...
```
컴파일 실행됨 (`$(OBJ)` 종속성을 만족시키기 위해 오브젝트 파일을 만듬)

make:
```c
❯ make
make[1]: 'all'을(를) 위해 할 일이 없습니다. /* libft */
```
오브젝트 파일을 만들지 않음

### 해결 방법
`$(LIBFT)` 레시피가 `$(NAME)` 레시피보다 위에 있어 우선순위가 더 높아 발생한 현상
`$(NAME)`을 위로 올려 우선순위를 높이면 해결됨
다음 PR에 변경점 추가 예정

**Comment by Hyoj-Kim** [comment]
아 맞아요 저도 make run이랑 make re 위주로만 쓰니까 몰랐는데 잘 안되긴 하더라구요 :sweat_smile: 
이슈 체크 굳굳 :+1:
