### ISSUE TITLE
token 및 AST 구조 논의

### ISSUE THREAD

**Issue by scarf005** [minishell-jiphyeonjeon/Rank03-Minishell#9]
### 개요
[bash-parser](https://vorpaljs.github.io/bash-parser-playground/) - [AST.md](https://github.com/vorpaljs/bash-parser/blob/master/documents/ast.md) 참고

### 논의 사항
- [ ] AST 구조체 선언
- [ ] `$` 처리 관련
  - 환경 변수 조회는 구현 왼료, #39 참고
  - AST 내의 Expansion(ParameterExpansion)을 통해 전달될 예정

**Comment by Hyoj-Kim** [comment]
## Script

```c
{
	type: 'Script',
	commands: Array<Pipeline | Command>
}
```

## Pipeline

```c
{
	type: 'Pipeline',
	commands: Array<Command>
}
```

## Command

```c
{
	type: 'Command',
	name: ?Word,
	prefix: Array<Redirect>,
	suffix: Array<Word | Redirect>
}
```

## Redirect

```c
{
	type: 'Redirect',
	op: string,
	file: word,
}
```

## Word

```c
{
	type: 'Word',
	text: String,
	expansion: Array<ParameterExpansion>
}
```

## ParameterExpansion

```c
{
	type: 'ParameterExpansion',
	parameter: string,
	loc: {
		start:Number,
		end:Number
	}
}
```
